<?php

$logDetailsModal = (require __DIR__ . '/../logs/table.php')['row_actions'][0]['modal'];

return [
    'key' => 'stask.tasks',
    'provider' => \Seiger\sTask\Tables\TasksTableData::class,
    'wire_target' => 'search,perPage,applyMultiFilter,applyDateRangeFilter,setSort,switchView,openActionModal,runRowAction',
    'per_page' => 30,
    'per_page_options' => [15, 30, 50, 100, 200],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'id_label',
    'default_direction' => 'desc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
        'placeholder' => 'sTask::global.search_tasks',
    ],
    'filters' => [
        [
            'state' => 'worker_id',
            'type' => 'multi-select',
            'icon' => 'cpu',
            'label' => 'sTask::global.worker',
            'searchable' => true,
            'default' => [],
        ],
        [
            'state' => 'action',
            'type' => 'multi-select',
            'icon' => 'bolt',
            'label' => 'sTask::global.action',
            'searchable' => true,
            'default' => [],
        ],
        [
            'state' => 'status',
            'type' => 'multi-select',
            'icon' => 'activity',
            'label' => 'sTask::global.status',
            'searchable' => false,
            'default' => [],
        ],
        [
            'state' => 'created_at',
            'type' => 'date-range',
            'icon' => 'calendar',
            'label' => 'sTask::global.created_range',
            'default' => ['from' => '', 'to' => ''],
        ],
    ],
    'columns' => [
        ['key' => 'id_label', 'type' => 'text', 'label' => 'ID', 'sortable' => true, 'sort_field' => 'id', 'default_direction' => 'desc'],
        ['key' => 'worker_title', 'type' => 'text', 'label' => 'sTask::global.worker', 'sortable' => true, 'sort_field' => 'identifier', 'meta_icon' => 'cpu'],
        ['key' => 'worker_identifier', 'type' => 'text', 'label' => 'sTask::global.identifier', 'sortable' => true, 'sort_field' => 'identifier'],
        ['key' => 'action', 'type' => 'text', 'label' => 'sTask::global.action', 'sortable' => true, 'sort_field' => 'action', 'meta_icon' => 'bolt'],
        ['key' => 'status_badge', 'type' => 'badge', 'label' => 'sTask::global.status', 'sortable' => true, 'sort_field' => 'status'],
        ['key' => 'progress_label', 'type' => 'text', 'label' => 'sTask::global.progress', 'cell_class' => 'stask-task-progress-cell', 'sortable' => true, 'sort_field' => 'progress', 'meta_icon' => 'percentage'],
        ['key' => 'started_by', 'type' => 'text', 'label' => 'sTask::global.started_by', 'sortable' => true, 'sort_field' => 'started_by', 'meta_icon' => 'user'],
        ['key' => 'message_text', 'type' => 'markdown', 'label' => 'sTask::global.message', 'cell_class' => 'stask-task-message-cell'],
        ['key' => 'start_at_label', 'type' => 'text', 'label' => 'sTask::global.start_at', 'class' => 'stask-task-time-column', 'cell_class' => 'stask-task-time-cell', 'sortable' => true, 'sort_field' => 'start_at', 'default_direction' => 'desc', 'meta_icon' => 'player-play'],
        ['key' => 'finished_at_label', 'type' => 'text', 'label' => 'sTask::global.finished_at', 'class' => 'stask-task-time-column', 'cell_class' => 'stask-task-time-cell', 'sortable' => true, 'sort_field' => 'finished_at', 'default_direction' => 'desc', 'meta_icon' => 'circle-check'],
    ],
    'list' => [
        'media' => true,
        'icon' => 'clipboard-list',
        'title' => 'id_label',
        'subtitle' => 'worker_title',
        'meta' => ['action', 'status_badge', 'progress_label', 'message_text'],
    ],
    'modal' => [
        'enabled' => true,
        'row_dblclick_action' => 'details',
        'size' => 'lg',
    ],
    'row_actions' => [
        [
            'key' => 'details',
            'type' => 'wire',
            'method' => 'openActionModal',
            'argument' => 'id',
            'action_argument' => true,
            'icon' => 'eye',
            'label' => 'sTask::global.details',
            'tone' => 'primary',
            'modal' => $logDetailsModal,
        ],
        [
            'key' => 'emergency_stop',
            'type' => 'wire',
            'method' => 'runRowAction',
            'provider' => 'emergencyStopTask',
            'argument' => 'id',
            'action_argument' => true,
            'disabled_field' => 'emergency_stop_disabled',
            'icon' => 'player-eject',
            'label' => 'sTask::global.emergency_stop_task',
            'tone' => 'danger',
        ],
    ],
];
