<?php

$logDetailsModal = (require __DIR__ . '/../logs/table.php')['row_actions'][0]['modal'];

return [
    'key' => 'stask.tasks',
    'provider' => \Seiger\sTask\Tables\TasksTableData::class,
    'wire_target' => 'search,perPage,applyMultiFilter,applyDateRangeFilter,setSort,switchView,openActionModal',
    'per_page' => 10,
    'per_page_options' => [10, 20, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'created_at_label',
    'default_direction' => 'desc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
        'placeholder' => 'sTask::global.search_tasks',
    ],
    'filters' => [
        [
            'state' => 'worker_id',
            'type' => 'multi-select',
            'icon' => 'cpu',
            'label' => 'sTask::global.worker',
            'searchable' => true,
            'default' => [],
        ],
        [
            'state' => 'action',
            'type' => 'multi-select',
            'icon' => 'activity',
            'label' => 'sTask::global.action',
            'searchable' => true,
            'default' => [],
        ],
        [
            'state' => 'status',
            'type' => 'multi-select',
            'icon' => 'activity',
            'label' => 'sTask::global.status',
            'searchable' => false,
            'default' => [],
        ],
        [
            'state' => 'priority',
            'type' => 'multi-select',
            'icon' => 'flag',
            'label' => 'sTask::global.priority',
            'searchable' => false,
            'default' => [],
        ],
        [
            'state' => 'attempts',
            'type' => 'multi-select',
            'icon' => 'repeat',
            'label' => 'sTask::global.attempts',
            'searchable' => false,
            'default' => [],
        ],
        [
            'state' => 'created_at',
            'type' => 'date-range',
            'icon' => 'calendar',
            'label' => 'sTask::global.created_range',
            'default' => ['from' => '', 'to' => ''],
        ],
    ],
    'columns' => [
        ['key' => 'id_label', 'type' => 'text', 'label' => 'ID', 'sortable' => true, 'sort_field' => 'id', 'default_direction' => 'desc'],
        ['key' => 'worker_title', 'type' => 'text', 'label' => 'sTask::global.worker', 'sortable' => true, 'sort_field' => 'identifier', 'meta_icon' => 'cpu'],
        ['key' => 'worker_identifier', 'type' => 'text', 'label' => 'sTask::global.identifier', 'sortable' => true, 'sort_field' => 'identifier'],
        ['key' => 'action', 'type' => 'text', 'label' => 'sTask::global.action', 'sortable' => true, 'sort_field' => 'action', 'meta_icon' => 'activity'],
        ['key' => 'status_badge', 'type' => 'badge', 'label' => 'sTask::global.status', 'sortable' => true, 'sort_field' => 'status'],
        ['key' => 'priority_badge', 'type' => 'badge', 'label' => 'sTask::global.priority', 'sortable' => true, 'sort_field' => 'priority'],
        ['key' => 'progress_label', 'type' => 'text', 'label' => 'sTask::global.progress', 'sortable' => true, 'sort_field' => 'progress', 'meta_icon' => 'percentage'],
        ['key' => 'attempts_label', 'type' => 'text', 'label' => 'sTask::global.attempts', 'sortable' => true, 'sort_field' => 'attempts', 'meta_icon' => 'repeat'],
        ['key' => 'started_by', 'type' => 'text', 'label' => 'sTask::global.started_by', 'sortable' => true, 'sort_field' => 'started_by', 'meta_icon' => 'user'],
        ['key' => 'message_excerpt', 'type' => 'text', 'label' => 'sTask::global.message'],
        ['key' => 'created_at_label', 'type' => 'text', 'label' => 'sTask::global.created', 'sortable' => true, 'sort_field' => 'created_at', 'default_direction' => 'desc', 'meta_icon' => 'calendar'],
        ['key' => 'start_at_label', 'type' => 'text', 'label' => 'sTask::global.start_at', 'sortable' => true, 'sort_field' => 'start_at', 'default_direction' => 'desc', 'meta_icon' => 'player-play'],
        ['key' => 'finished_at_label', 'type' => 'text', 'label' => 'sTask::global.finished_at', 'sortable' => true, 'sort_field' => 'finished_at', 'default_direction' => 'desc', 'meta_icon' => 'circle-check'],
        ['key' => 'updated_at_label', 'type' => 'text', 'label' => 'sTask::global.updated', 'sortable' => true, 'sort_field' => 'updated_at', 'default_direction' => 'desc', 'meta_icon' => 'refresh'],
    ],
    'list' => [
        'media' => true,
        'icon' => 'list-checks',
        'title' => 'id_label',
        'subtitle' => 'worker_title',
        'meta' => ['action', 'status_badge', 'priority_badge', 'progress_label', 'attempts_label', 'created_at_label'],
    ],
    'modal' => [
        'enabled' => true,
        'row_dblclick_action' => 'details',
        'size' => 'lg',
    ],
    'row_actions' => [
        [
            'key' => 'details',
            'type' => 'wire',
            'method' => 'openActionModal',
            'argument' => 'id',
            'action_argument' => true,
            'icon' => 'eye',
            'label' => 'sTask::global.details',
            'tone' => 'primary',
            'modal' => $logDetailsModal,
        ],
    ],
];
