<?php return [
    'key' => 'stask.workers',
    'provider' => \Seiger\sTask\Tables\WorkersTableData::class,
    'wire_target' => 'search,perPage,applyMultiFilter,setSort,switchView,openEditModal,saveModal,closeModal,runTableAction,runRowAction,togglePublished,toggleVisibility',
    'per_page' => 30,
    'per_page_options' => [15, 30, 50, 100, 200],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'position',
    'default_direction' => 'asc',
    'row_states' => [
        ['field' => 'active', 'value' => false, 'class' => 'is-dimmed'],
    ],
    'search' => [
        'enabled' => true,
        'state' => 'search',
        'placeholder' => 'sTask::global.search_workers',
    ],
    'actions' => [
        [
            'key' => 'refresh_registry',
            'type' => 'wire',
            'provider' => 'refreshWorkerRegistry',
            'icon' => 'database-cog',
            'label' => 'sTask::global.refresh_worker_registry',
            'tone' => 'neutral',
            'icon_only' => true,
            'attributes' => [
                'style' => 'color: var(--evo-ui-muted);',
            ],
        ],
        [
            'key' => 'run',
            'type' => 'wire',
            'provider' => 'runSelectedWorker',
            'attributes_provider' => 'runSelectedWorkerAttributes',
            'icon' => 'player-play',
            'label' => 'sTask::global.run_task',
            'tone' => 'info',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'toggle_active',
            'type' => 'wire',
            'provider' => 'toggleSelectedActive',
            'icon' => 'power',
            'label' => 'sTask::global.toggle_active',
            'tone' => 'warning',
            'icon_only' => true,
            'selection' => 'single',
        ],
    ],
    'filters' => [
        [
            'state' => 'active',
            'type' => 'multi-select',
            'icon' => 'power',
            'label' => 'sTask::global.worker_status',
            'searchable' => false,
            'default' => [],
        ],
        [
            'state' => 'class_exists',
            'type' => 'multi-select',
            'icon' => 'shield-check',
            'label' => 'sTask::global.class_exists',
            'searchable' => false,
            'default' => [],
        ],
        [
            'state' => 'hidden',
            'type' => 'multi-select',
            'icon' => 'eye',
            'label' => 'sTask::global.visibility',
            'searchable' => false,
            'default' => [],
        ],
    ],
    'columns' => [
        ['key' => 'identifier', 'type' => 'text', 'label' => 'sTask::global.identifier', 'sortable' => true, 'sort_field' => 'identifier', 'meta_icon' => 'id'],
        ['key' => 'worker_title', 'type' => 'text', 'label' => 'sTask::global.worker', 'cell_class' => 'evo-ui-table__title-column evo-ui-table__title-text', 'sortable' => true, 'sort_field' => 'title'],
        ['key' => 'description_excerpt', 'type' => 'text', 'label' => 'sTask::global.description'],
        ['key' => 'schedule_label', 'type' => 'text', 'label' => 'sTask::global.schedule', 'sortable' => false, 'meta_icon' => 'clock'],
        ['key' => 'supervisor_state_badge', 'type' => 'badge', 'label' => 'sTask::global.supervisor_state', 'sortable' => false],
        ['key' => 'tasks_count_label', 'type' => 'text', 'label' => 'sTask::global.tasks_count', 'sortable' => true, 'sort_field' => 'tasks_count', 'meta_icon' => 'list-checks'],
        ['key' => 'last_action_label', 'type' => 'text', 'label' => 'sTask::global.task', 'sortable' => false],
        ['key' => 'last_run_at_label', 'type' => 'text', 'label' => 'sTask::global.last_run', 'sortable' => false, 'meta_icon' => 'clock-play'],
    ],
    'list' => [
        'media' => true,
        'icon' => 'cpu',
        'title' => 'worker_title',
        'subtitle' => 'description',
        'meta' => ['schedule_label', 'identifier', 'tasks_count_label', 'last_action_label', 'last_run_at_label'],
    ],
    'modal' => [
        'enabled' => true,
        'row_dblclick' => true,
        'icon' => 'cpu',
        'size' => 'lg',
        'title_edit' => 'sTask::global.edit_worker',
        'submit_label' => 'evo::global.action_save',
        'cancel_label' => 'evo::global.action_cancel',
        'fields' => [
            ['name' => 'title', 'type' => 'static', 'label' => 'sTask::global.worker'],
            ['name' => 'identifier', 'type' => 'static', 'label' => 'sTask::global.identifier'],
            ['name' => 'scope', 'type' => 'static', 'label' => 'sTask::global.scope'],
            ['name' => 'active', 'type' => 'checkbox', 'label' => 'sTask::global.active'],
            ['name' => 'hidden', 'type' => 'checkbox', 'label' => 'sTask::global.hidden'],
            ['name' => 'position', 'type' => 'number', 'label' => 'sTask::global.default_position', 'min' => 0],
            ['name' => 'schedule_enabled', 'type' => 'checkbox', 'label' => 'sTask::global.enable_auto_run'],
            [
                'name' => 'schedule_type',
                'type' => 'select',
                'label' => 'sTask::global.schedule_type',
                'visible_if' => ['field' => 'schedule_enabled', 'value' => true],
                'options_provider' => 'scheduleTypeOptions',
            ],
            [
                'name' => 'schedule_datetime',
                'type' => 'text',
                'label' => 'sTask::global.datetime_launch',
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'once'],
                ],
            ],
            [
                'name' => 'schedule_frequency',
                'type' => 'select',
                'label' => 'sTask::global.frequency',
                'visible_if' => ['field' => 'schedule_enabled', 'value' => true],
                'visible_if_any' => [
                    ['field' => 'schedule_type', 'value' => 'periodic'],
                    ['field' => 'schedule_type', 'value' => 'regular'],
                ],
                'options_provider' => 'scheduleFrequencyOptions',
            ],
            [
                'name' => 'schedule_hourly_minute',
                'type' => 'number',
                'label' => 'sTask::global.time_launch',
                'placeholder' => '30',
                'addon_prefix' => '*:',
                'min' => 0,
                'max' => 59,
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'periodic'],
                    ['field' => 'schedule_frequency', 'value' => 'hourly'],
                ],
            ],
            [
                'name' => 'schedule_time',
                'type' => 'text',
                'label' => 'sTask::global.time_launch',
                'placeholder' => '09:30',
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'periodic'],
                ],
                'visible_if_any' => [
                    ['field' => 'schedule_frequency', 'value' => 'daily'],
                    ['field' => 'schedule_frequency', 'value' => 'weekly'],
                    ['field' => 'schedule_frequency', 'value' => 'monthly'],
                ],
            ],
            [
                'name' => 'schedule_start_time',
                'type' => 'text',
                'label' => 'sTask::global.start_time',
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'regular'],
                ],
            ],
            [
                'name' => 'schedule_end_time',
                'type' => 'text',
                'label' => 'sTask::global.end_time',
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'regular'],
                ],
            ],
            [
                'name' => 'supervisor_key',
                'type' => 'static',
                'label' => 'sTask::global.supervisor_key',
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'supervisor'],
                ],
            ],
            [
                'name' => 'supervisor_state_badge',
                'type' => 'badge',
                'label' => 'sTask::global.supervisor_state',
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'supervisor'],
                ],
            ],
            [
                'name' => 'supervisor_pid',
                'type' => 'static',
                'label' => 'sTask::global.supervisor_pid',
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'supervisor'],
                ],
            ],
            [
                'name' => 'supervisor_heartbeat_at',
                'type' => 'static',
                'label' => 'sTask::global.supervisor_heartbeat',
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'supervisor'],
                ],
            ],
            [
                'name' => 'supervisor_uptime',
                'type' => 'static',
                'label' => 'sTask::global.supervisor_uptime',
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'supervisor'],
                ],
            ],
            [
                'name' => 'supervisor_last_diagnostic',
                'type' => 'static',
                'label' => 'sTask::global.supervisor_last_diagnostic',
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'supervisor'],
                ],
            ],
            [
                'name' => 'supervisor_last_transition_at',
                'type' => 'static',
                'label' => 'sTask::global.supervisor_last_transition',
                'visible_if_all' => [
                    ['field' => 'schedule_enabled', 'value' => true],
                    ['field' => 'schedule_type', 'value' => 'supervisor'],
                ],
            ],
            ['name' => 'settings_payload', 'type' => 'textarea', 'label' => 'sTask::global.additional_settings', 'rows' => 8, 'help' => 'sTask::global.additional_settings_help'],
            ['name' => 'class', 'type' => 'code', 'label' => 'sTask::global.worker_class'],
            ['name' => 'description', 'type' => 'static', 'label' => 'sTask::global.worker_description'],
        ],
    ],
    'row_actions' => [
        [
            'key' => 'run',
            'type' => 'wire',
            'method' => 'runRowAction',
            'provider' => 'runWorker',
            'argument' => 'id',
            'action_argument' => true,
            'disabled_field' => 'run_disabled',
            'icon' => 'player-play',
            'label' => 'sTask::global.run_task',
            'tone' => 'info',
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'argument' => 'id',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
        ],
        [
            'key' => 'toggle_hidden',
            'type' => 'wire',
            'method' => 'runRowAction',
            'provider' => 'toggleVisibility',
            'argument' => 'id',
            'action_argument' => true,
            'icon_field' => 'hidden',
            'icon_true' => 'eye',
            'icon_false' => 'eye-off',
            'label_field' => 'hidden',
            'label_true' => 'sTask::global.show_worker',
            'label_false' => 'sTask::global.hide_worker',
            'tone_field' => 'hidden',
            'tone_true' => 'success',
            'tone_false' => 'warning',
        ],
        [
            'key' => 'toggle_active',
            'type' => 'wire',
            'method' => 'togglePublished',
            'argument' => 'id',
            'icon_field' => 'active',
            'icon_true' => 'power',
            'icon_false' => 'power',
            'label_field' => 'active',
            'label_true' => 'sTask::global.deactivate',
            'label_false' => 'sTask::global.activate',
            'tone_field' => 'active',
            'tone_true' => 'warning',
            'tone_false' => 'success',
        ],
    ],
];
