<?php

return [
    'key' => 'stask.workers',
    'provider' => \Seiger\sTask\Tables\WorkersTableData::class,
    'wire_target' => 'search,perPage,applyMultiFilter,setSort,switchView,openEditModal,saveModal,closeModal,runRowAction,togglePublished',
    'per_page' => 10,
    'per_page_options' => [10, 20, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'position',
    'default_direction' => 'asc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
        'placeholder' => 'sTask::global.search_workers',
    ],
    'actions' => [
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'run',
            'type' => 'wire',
            'provider' => 'runSelectedWorker',
            'icon' => 'play',
            'label' => 'sTask::global.run_task',
            'tone' => 'info',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'toggle_active',
            'type' => 'wire',
            'provider' => 'toggleSelectedActive',
            'icon' => 'power',
            'label' => 'sTask::global.toggle_active',
            'tone' => 'warning',
            'icon_only' => true,
            'selection' => 'single',
        ],
    ],
    'filters' => [
        [
            'state' => 'active',
            'type' => 'multi-select',
            'icon' => 'power',
            'label' => 'sTask::global.worker_status',
            'searchable' => false,
            'default' => [],
        ],
        [
            'state' => 'class_exists',
            'type' => 'multi-select',
            'icon' => 'shield-check',
            'label' => 'sTask::global.class_exists',
            'searchable' => false,
            'default' => [],
        ],
        [
            'state' => 'hidden',
            'type' => 'multi-select',
            'icon' => 'eye',
            'label' => 'sTask::global.visibility',
            'searchable' => false,
            'default' => [],
        ],
    ],
    'columns' => [
        ['key' => 'worker_link', 'type' => 'link', 'label' => 'sTask::global.worker', 'class' => 'evo-ui-table__title-column', 'sortable' => true, 'sort_field' => 'title'],
        ['key' => 'description_excerpt', 'type' => 'text', 'label' => 'sTask::global.description'],
        ['key' => 'identifier', 'type' => 'text', 'label' => 'sTask::global.identifier', 'sortable' => true, 'sort_field' => 'identifier', 'meta_icon' => 'id'],
        ['key' => 'scope', 'type' => 'text', 'label' => 'sTask::global.scope', 'sortable' => true, 'sort_field' => 'scope', 'meta_icon' => 'folder'],
        ['key' => 'active_badge', 'type' => 'badge', 'label' => 'sTask::global.active', 'sortable' => true, 'sort_field' => 'active'],
        ['key' => 'class_exists_badge', 'type' => 'badge', 'label' => 'sTask::global.class_exists', 'sortable' => true, 'sort_field' => 'class_exists'],
        ['key' => 'hidden_badge', 'type' => 'badge', 'label' => 'sTask::global.visibility', 'sortable' => true, 'sort_field' => 'hidden'],
        ['key' => 'tasks_count', 'type' => 'text', 'label' => 'sTask::global.tasks_count', 'sortable' => true, 'sort_field' => 'tasks_count', 'meta_icon' => 'list-checks'],
        ['key' => 'last_task_badge', 'type' => 'badge', 'label' => 'sTask::global.last_task', 'sortable' => false],
        ['key' => 'position', 'type' => 'text', 'label' => 'sTask::global.position', 'sortable' => true, 'sort_field' => 'position'],
        ['key' => 'updated_at_label', 'type' => 'text', 'label' => 'sTask::global.updated', 'sortable' => true, 'sort_field' => 'updated_at', 'default_direction' => 'desc', 'meta_icon' => 'refresh'],
    ],
    'list' => [
        'media' => true,
        'icon' => 'cpu',
        'title' => 'worker_link',
        'subtitle' => 'description',
        'meta' => ['identifier', 'scope', 'active_badge', 'class_exists_badge', 'tasks_count', 'last_task_badge'],
    ],
    'modal' => [
        'enabled' => true,
        'row_dblclick' => true,
        'icon' => 'cpu',
        'size' => 'lg',
        'title_edit' => 'sTask::global.edit_worker',
        'submit_label' => 'evo::global.action_save',
        'cancel_label' => 'evo::global.action_cancel',
        'fields' => [
            ['name' => 'title', 'type' => 'static', 'label' => 'sTask::global.worker'],
            ['name' => 'identifier', 'type' => 'static', 'label' => 'sTask::global.identifier'],
            ['name' => 'scope', 'type' => 'static', 'label' => 'sTask::global.scope'],
            ['name' => 'active', 'type' => 'checkbox', 'label' => 'sTask::global.active'],
            ['name' => 'hidden', 'type' => 'checkbox', 'label' => 'sTask::global.hidden'],
            ['name' => 'position', 'type' => 'number', 'label' => 'sTask::global.position', 'min' => 0],
            ['name' => 'schedule_enabled', 'type' => 'checkbox', 'label' => 'sTask::global.enable_auto_run'],
            [
                'name' => 'schedule_type',
                'type' => 'select',
                'label' => 'sTask::global.schedule_type',
                'options' => [
                    ['value' => 'manual', 'label' => 'sTask::global.schedule_manual'],
                    ['value' => 'once', 'label' => 'sTask::global.schedule_once'],
                    ['value' => 'periodic', 'label' => 'sTask::global.schedule_periodic'],
                    ['value' => 'regular', 'label' => 'sTask::global.schedule_regular'],
                ],
            ],
            ['name' => 'schedule_datetime', 'type' => 'text', 'label' => 'sTask::global.datetime_launch'],
            [
                'name' => 'schedule_frequency',
                'type' => 'select',
                'label' => 'sTask::global.frequency',
                'options' => [
                    ['value' => 'hourly', 'label' => 'sTask::global.frequency_hourly'],
                    ['value' => 'daily', 'label' => 'sTask::global.frequency_daily'],
                    ['value' => 'weekly', 'label' => 'sTask::global.frequency_weekly'],
                ],
            ],
            ['name' => 'schedule_time', 'type' => 'text', 'label' => 'sTask::global.time_launch'],
            ['name' => 'schedule_start_time', 'type' => 'text', 'label' => 'sTask::global.start_time'],
            ['name' => 'schedule_end_time', 'type' => 'text', 'label' => 'sTask::global.end_time'],
            [
                'name' => 'schedule_interval',
                'type' => 'select',
                'label' => 'sTask::global.interval',
                'options' => [
                    ['value' => 'every_5min', 'label' => 'sTask::global.interval_5min'],
                    ['value' => 'every_15min', 'label' => 'sTask::global.interval_15min'],
                    ['value' => 'every_30min', 'label' => 'sTask::global.interval_30min'],
                    ['value' => 'hourly', 'label' => 'sTask::global.interval_hourly'],
                ],
            ],
            ['name' => 'class', 'type' => 'code', 'label' => 'sTask::global.worker_class'],
            ['name' => 'description', 'type' => 'static', 'label' => 'sTask::global.worker_description'],
            ['name' => 'settings_url', 'type' => 'static', 'label' => 'sTask::global.full_worker_settings'],
        ],
    ],
    'row_actions' => [
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'argument' => 'id',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
        ],
        [
            'key' => 'run',
            'type' => 'wire',
            'method' => 'runRowAction',
            'provider' => 'runWorker',
            'argument' => 'id',
            'action_argument' => true,
            'disabled_field' => 'run_disabled',
            'icon' => 'play',
            'label' => 'sTask::global.run_task',
            'tone' => 'info',
        ],
        [
            'key' => 'toggle_active',
            'type' => 'wire',
            'method' => 'togglePublished',
            'argument' => 'id',
            'icon_field' => 'active',
            'icon_true' => 'power',
            'icon_false' => 'power',
            'label_field' => 'active',
            'label_true' => 'sTask::global.deactivate',
            'label_false' => 'sTask::global.activate',
            'tone_field' => 'active',
            'tone_true' => 'warning',
            'tone_false' => 'success',
        ],
    ],
];
